# Generated by Django 5.2.4 on 2025-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_horariofuncionamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbearia',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AddField(
            model_name='barbearia',
            name='email_notificacoes',
            field=models.EmailField(blank=True, help_text='Email para receber notificações de novos agendamentos', max_length=254, null=True),
        ),
    ]
