# Generated by Django 5.2.4 on 2025-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0003_alter_barbearia_options_barbearia_email_notificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='tema',
            field=models.CharField(choices=[('classico', 'Clássico (Azul e Branco)'), ('moderno', 'Moderno (Preto e Dourado)'), ('elegante', 'Elegante (Cinza e Verde)'), ('vibrante', 'Vibrante (Roxo e Rosa)'), ('rustico', 'Rústico (Marrom e Laranja)'), ('minimalista', 'Minimalista (Branco e Preto)'), ('tropical', 'Tropical (Verde e Azul)'), ('vintage', 'Vintage (Sépia e Bege)')], default='classico', help_text='Tema visual do estabelecimento', max_length=20),
        ),
    ]
