# Generated by Django 5.2.4 on 2025-08-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0004_barbearia_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=50, unique=True)),
                ('max_servicos', models.PositiveIntegerField(help_text='Máximo de serviços que podem ser cadastrados')),
                ('max_profissionais', models.PositiveIntegerField(help_text='Máximo de profissionais que podem ser cadastrados')),
                ('permite_temas_personalizados', models.BooleanField(default=False, help_text='Permite usar temas personalizados')),
                ('preco_mensal', models.DecimalField(decimal_places=2, help_text='Preço mensal do plano', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.AddField(
            model_name='barbearia',
            name='plano',
            field=models.ForeignKey(blank=True, help_text='Plano de assinatura do estabelecimento', null=True, on_delete=django.db.models.deletion.PROTECT, to='barbearias.plano'),
        ),
    ]
