# Generated by Django 5.2.4 on 2025-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0005_plano_barbearia_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('vip', 'VIP')], default='basico', help_text='Tipo do serviço (define qual plano pode agendar)', max_length=20),
        ),
    ]
