# Generated by Django 5.2.4 on 2025-08-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0006_servico_tipo_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbearia',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tipo_servico',
        ),
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
