# Generated by Django 5.2.4 on 2025-08-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0007_remove_barbearia_plano_remove_servico_tipo_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_profissionais', models.PositiveIntegerField(help_text='Número máximo de profissionais permitidos (0 = ilimitado)')),
                ('descricao', models.TextField()),
                ('agendamento_online', models.BooleanField(default=True)),
                ('gestao_agenda', models.BooleanField(default=True)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('notificacoes_sms', models.BooleanField(default=False)),
                ('integracao_google_calendar', models.BooleanField(default=False)),
                ('relatorios_basicos', models.BooleanField(default=False)),
                ('relatorios_avancados', models.BooleanField(default=False)),
                ('integracao_pagamento', models.BooleanField(default=False)),
                ('personalizacao_completa', models.BooleanField(default=False)),
                ('suporte_prioritario', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['preco_mensal'],
            },
        ),
        migrations.AddField(
            model_name='barbearia',
            name='plano',
            field=models.ForeignKey(blank=True, help_text='Plano de assinatura do estabelecimento', null=True, on_delete=django.db.models.deletion.PROTECT, to='barbearias.plano'),
        ),
    ]
