# Generated by Django 5.2.4 on 2025-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='notificacao_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
