# Generated by Django 5.2.4 on 2025-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_notificacao_enviada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='email_cliente',
            field=models.EmailField(help_text='Email para receber lembretes do agendamento', max_length=254, null=True),
        ),
    ]
